sandbox-update-torbrowser: Add locking, avoid leftover msgprogress instances, fix broken msgdispatcher invocation

diff --git a/usr/libexec/tb-updater/sandbox-update-torbrowser b/usr/libexec/tb-updater/sandbox-update-torbrowser
--- a/usr/libexec/tb-updater/sandbox-update-torbrowser
+++ b/usr/libexec/tb-updater/sandbox-update-torbrowser
@@ -5,7 +5,7 @@
 
 ## NOTE: Do NOT use `sudo` in this script! It will be run by tb-updater's
 ## postinst, which may run under a torsocks'd apt due to uwtwrapper. torsocks
-## breaks sudo. Use setpriv instead, as this works with torsocks.
+## breaks sudo. Use setpriv-tb-updater instead, as this works with torsocks.
 
 ## TODO: Make this work with more than just Tor Browser.
 
@@ -22,30 +22,21 @@ source /usr/libexec/helper-scripts/has.sh
 ## shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/log_run_die.sh
 source /usr/libexec/helper-scripts/log_run_die.sh
 
+## shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/light_sleep.bsh
+source /usr/libexec/helper-scripts/light_sleep.bsh
+
+## shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/lockfile.sh
+source /usr/libexec/helper-scripts/lockfile.sh
+
 has setfacl
 
 tb_updater_home='/var/lib/tb-updater/work'
 root_browser_dir='/var/cache/tb-binary'
-tb_updater_uid="$(id -u tb-updater)"
-if [ -z "${tb_updater_uid}" ]; then
-   log error "Unable to get UID of account 'tb-updater'! Exiting."
-   exit 1
-fi
-tb_updater_gid="$(id -g tb-updater)"
-if [ -z "${tb_updater_gid}" ]; then
-   log error "Unable to get GID of account 'tb-updater'! Exiting."
-   exit 1
-fi
 tb_updater_run_dir="/run/user/$(id -u tb-updater)"
 wl_sock="${tb_updater_run_dir}/wayland-0"
 use_x11_gui='false'
-msgdispatcher_cgroup=''
-
-setpriv_tb_updater() {
-  log notice "Executing under account tb-updater: '$*'"
-  setpriv --reuid "${tb_updater_uid}" --regid "${tb_updater_gid}" \
-    --init-groups --reset-env -- "$@"
-}
+tb_updater_cgroup=''
+tb_updater_cgroup_name=''
 
 cleanup_dir_as_tb_updater() {
   local target_dir
@@ -65,20 +56,43 @@ cleanup_dir_as_tb_updater() {
   log notice "Deleting contents of directory '${target_dir}' using account 'tb-updater'."
   shopt -s dotglob
   shopt -s nullglob
-  setpriv_tb_updater safe-rm --recursive --force --one-file-system \
+  /usr/libexec/tb-updater/setpriv-tb-updater \
+    safe-rm --recursive --force --one-file-system \
     -- "${target_dir}"/*
   shopt -u dotglob
   shopt -u nullglob
 }
 
 cleanup() {
-  local xhost_output
+  local xhost_output cgroup_empty_str inotifywait_subshell_pid \
+    inotifywait_fd
 
-  if [ -n "${msgdispatcher_cgroup}" ]; then
-    printf '%s\n' '1' > "${msgdispatcher_cgroup}/cgroup.kill" \
-      || log warning "Cannot kill msgdispatcher cgroup at '${msgdispatcher_cgroup}'!"
-    rmdir "${msgdispatcher_cgroup}" \
-      || log warning "Cannot remove msgdispatcher cgroup at '${msgdispatcher_cgroup}'!"
+  if [ -n "${tb_updater_cgroup}" ] && validate_uuid "${tb_updater_cgroup_name}"; then
+    cgroup_empty_str="populated 0
+frozen 0"
+    (
+      exec {inotifywait_fd}< <(inotifywait --quiet --monitor --event modify "${tb_updater_cgroup}/cgroup.events")
+      # shellcheck disable=SC2064
+      trap "kill -s KILL $!" EXIT INT TERM
+      while IFS=$'\n' read -r _; do
+        if [ "$(cat "${tb_updater_cgroup}/cgroup.events")" = "${cgroup_empty_str}" ]; then
+          rmdir "${tb_updater_cgroup}" \
+            || log warn "Cannot remove tb-updater cgroup at '${tb_updater_cgroup}'!"
+          break
+        fi
+      done <&"${inotifywait_fd}"
+    ) &
+    inotifywait_subshell_pid="$!"
+    ## inotifywait itself requires some time to initialize. 1/20th of a second
+    ## seems to be enough on rather slow hardware. so use 1/10th of a second
+    ## for good measure.
+    light_sleep 0.1
+    if printf '%s\n' '1' > "${tb_updater_cgroup}/cgroup.kill"; then
+      wait "${inotifywait_subshell_pid}"
+    else
+      log warn "Cannot kill tb-updater cgroup at '${tb_updater_cgroup}'!"
+      kill "${inotifywait_subshell_pid}"
+    fi
   fi
 
   if [ -S "${wl_sock}" ] \
@@ -152,6 +166,14 @@ is_gui_enabled() {
     return
   fi
   printf '%s\n' 'false'
+}
+
+validate_uuid() {
+  if [[ "$1" \
+    =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
+    return 0
+  fi
+  return 1
 }
 
 sandbox_update_torbrowser() {
@@ -296,17 +318,22 @@ sandbox_update_torbrowser() {
 
   if [ "${gui_ready}" = 'true' ]; then
     if [ "${use_x11_gui}" = 'true' ]; then
-      msgdispatcher_cgroup="$(/usr/libexec/helper-scripts/run-in-new-cgroup \
+      tb_updater_cgroup="$(/usr/libexec/helper-scripts/run-in-cgroup \
         --detach \
         -- \
-        setpriv_tb_updater \
+        /usr/libexec/tb-updater/setpriv-tb-updater \
         env \
         XDG_RUNTIME_DIR="${tb_updater_run_dir}" \
         DISPLAY="${DISPLAY}" \
         QT_QPA_PLATFORM='xcb' \
         GDK_BACKEND='x11' \
         /usr/libexec/msgcollector/msgdispatcher)"
-      setpriv_tb_updater \
+      tb_updater_cgroup_name="${tb_updater_cgroup##*/}"
+      validate_uuid "${tb_updater_cgroup_name}"
+      /usr/libexec/helper-scripts/run-in-cgroup \
+        --cgroup-name "${tb_updater_cgroup_name}" \
+        -- \
+        /usr/libexec/tb-updater/setpriv-tb-updater \
         env \
         XDG_RUNTIME_DIR="${tb_updater_run_dir}" \
         DISPLAY="${DISPLAY}" \
@@ -314,17 +341,22 @@ sandbox_update_torbrowser() {
         GDK_BACKEND='x11' \
         /usr/bin/update-torbrowser "$@"
     else
-      msgdispatcher_cgroup="$(/usr/libexec/helper-scripts/run-in-new-cgroup \
+      tb_updater_cgroup="$(/usr/libexec/helper-scripts/run-in-cgroup \
         --detach \
         -- \
-        setpriv_tb_updater \
+        /usr/libexec/tb-updater/setpriv-tb-updater \
         env \
         XDG_RUNTIME_DIR="${tb_updater_run_dir}" \
         WAYLAND_DISPLAY='wayland-0' \
         QT_QPA_PLATFORM='wayland' \
         GDK_BACKEND='wayland' \
         /usr/libexec/msgcollector/msgdispatcher)"
-      setpriv_tb_updater \
+      tb_updater_cgroup_name="${tb_updater_cgroup##*/}"
+      validate_uuid "${tb_updater_cgroup_name}"
+      /usr/libexec/helper-scripts/run-in-cgroup \
+        --cgroup-name "${tb_updater_cgroup_name}" \
+        -- \
+        /usr/libexec/tb-updater/setpriv-tb-updater \
         env \
         XDG_RUNTIME_DIR="${tb_updater_run_dir}" \
         WAYLAND_DISPLAY='wayland-0' \
@@ -333,7 +365,7 @@ sandbox_update_torbrowser() {
         /usr/bin/update-torbrowser "$@"
     fi
   else
-    setpriv_tb_updater /usr/bin/update-torbrowser "$@"
+    /usr/libexec/tb-updater/setpriv-tb-updater /usr/bin/update-torbrowser "$@"
   fi
 
   if [ -d "${tb_updater_home}/.tb/tor-browser" ] && [ -d "${tb_updater_home}/.cache/tb" ]; then
