* port to new version file location and format
since RecommendedTBBVersions file was abolished by upstream

https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/33521

https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions/
https://web.archive.org/web/20201210123314/https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions/

* Show only 1 online detected version instead of multiple online detected versions.

This is to keep the implementation simple since the new version file by
upstream shows only one version per release channel.

* code simplification
* refactoring

https://forums.whonix.org/t/update-torbrowser-does-not-see-version-10-0-6/10711

diff --git a/usr/share/tb-updater/unit_test b/usr/share/tb-updater/unit_test
--- a/usr/share/tb-updater/unit_test
+++ b/usr/share/tb-updater/unit_test
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
+## See the file COPYING for copying conditions.
+
 set -e
 
 mydir="$( cd "$( dirname "$0" )" && pwd )"
@@ -10,17 +13,36 @@ cd ..
 
 source ./usr/lib/tbbversion_parser
 
-for RecommendedTBBVersions in ./usr/share/tb-updater/unit-test/RecommendedTBBVersions ./usr/share/tb-updater/unit-test/RecommendedTBBVersions2 ; do
-   test -f "$RecommendedTBBVersions"
+####
 
-   tbbversion
+RecommendedTBBVersions="./usr/share/tb-updater/unit-test/RecommendedTBBVersions"
+test -f "$RecommendedTBBVersions"
 
-   echo "tbb_recommended_versions_list: $tbb_recommended_versions_list"
+tbbversion
 
-   for tbb_version in $tbb_recommended_versions_list; do
-      echo "tbb_version: $tbb_version"
-   done
-   echo "----------"
-done
+if [ "$tbb_version" = "10.0.6" ]; then
+   true "$0: INFO: OK"
+else
+   echo "$0: tbb_version: $tbb_version"
+   echo "$0: ERROR 1!"
+   exit 1
+fi
 
-echo "OK"
+####
+
+RecommendedTBBVersions="./usr/share/tb-updater/unit-test/RecommendedTBBVersions2"
+test -f "$RecommendedTBBVersions"
+
+tbbversion
+
+if [ "$tbb_version" = "UNKNOWN" ]; then
+   true "$0: INFO: OK"
+else
+   echo "$0: tbb_version: $tbb_version"
+   echo "$0: ERROR 2!"
+   exit 1
+fi
+
+####
+
+true "$0: INFO: OK"
