changed default data dir to ~/.tb and cache dir to ~/.cache/tb - https://phabricator.whonix.org/T338

diff --git a/usr/bin/update-torbrowser b/usr/bin/update-torbrowser
--- a/usr/bin/update-torbrowser
+++ b/usr/bin/update-torbrowser
@@ -53,8 +53,8 @@ tb_error_handler() {
 <br></br>## bash -x $SCRIPTNAME
 <br></br>###########################################################</p>"
 
-   mkdir --parents ~/".tb"
-   echo "$MSG" >> ~/".tb/torbrowser_updater_error.log"
+   mkdir --parents ~/".cache/tb"
+   echo "$MSG" >> ~/".cache/tb/torbrowser_updater_error.log"
 
    if [ "$progressbaridx" = "" ]; then
       true
@@ -353,13 +353,15 @@ tb_config_folder_parser() {
 tb_preparation() {
    ## Workaround for CI compatibility.
    if [ "$CI" = "true" ]; then
-      [ -n "$tb_home_folder" ] || tb_home_folder=/home/user
+      [ -n "$tb_home_folder" ] || tb_home_folder=/home/user/.tb
+      [ -n "$tb_cache_folder" ] || tb_cache_folder=/home/user/.cache/tb
    else
-      [ -n "$tb_home_folder" ] || tb_home_folder=~
+      [ -n "$tb_home_folder" ] || tb_home_folder=~/.tb
+      [ -n "$tb_cache_folder" ] || tb_cache_folder=~/.cache/tb
    fi
 
    ## Required for /usr/lib/anon-shared-helper-scripts/tor_bootstrap_check.bsh.
-   TEMP_DIR="$tb_home_folder/.tb/temp_dir"
+   TEMP_DIR="$tb_cache_folder/temp_dir"
    export TEMP_DIR
    rm --recursive --force "$TEMP_DIR"
    mkdir --parents "$TEMP_DIR"
@@ -491,7 +493,8 @@ tb_preparation() {
    ## Export CURL variable, so it can be read by $CURL_PRGRS.
    export CURL
 
-   mkdir --parents "$tb_home_folder/.tb"
+   mkdir --parents "$tb_home_folder"
+   mkdir --parents "$tb_cache_folder"
 
    ## {{ Download from the torproject.org clearnet by default instead from
    ##    their hidden service.
@@ -512,7 +515,7 @@ tb_preparation() {
    fi
 
    ## Also used by function tbbversion.
-   [ -n "$RecommendedTBBVersions" ] || RecommendedTBBVersions="$tb_home_folder/.tb/RecommendedTBBVersions"
+   [ -n "$RecommendedTBBVersions" ] || RecommendedTBBVersions="$tb_cache_folder/RecommendedTBBVersions"
 }
 
 tb_connectivity_checks_tor() {
@@ -599,7 +602,7 @@ tb_connectivity_checks_curl() {
    ## Export CURL_PRGRS_MAX_FILE_SIZE_BYTES, so $CURL_PRGRS can read it.
    export CURL_PRGRS_MAX_FILE_SIZE_BYTES="2097152"
    ## Export CURL_OUT_FILE, so $CURL_PRGRS can read it.
-   export CURL_OUT_FILE="$tb_home_folder/.tb/tbb_remote_folder"
+   export CURL_OUT_FILE="$tb_cache_folder/tbb_remote_folder"
    curl_download_max_time="180"
    curl_download_target_url="$TBB_REMOTE_FOLDER"
    tb_download_common_exit_on_fail="false"
@@ -888,7 +891,7 @@ Downloading:
    ## Export CURL_PRGRS_MAX_FILE_SIZE_BYTES, so $CURL_PRGRS can read it.
    export CURL_PRGRS_MAX_FILE_SIZE_BYTES="2097152"
    ## Export CURL_OUT_FILE, so $CURL_PRGRS can read it.
-   export CURL_OUT_FILE="$tb_home_folder/.tb/$TBB_SIG_FILENAME"
+   export CURL_OUT_FILE="$tb_cache_folder/$TBB_SIG_FILENAME"
    curl_download_max_time="180"
    curl_download_target_url="$TBB_SIG_LINK"
    tb_download_common_exit_on_fail="8"
@@ -910,7 +913,7 @@ Downloading:
    ## Export CURL_PRGRS_MAX_FILE_SIZE_BYTES, so $CURL_PRGRS can read it.
    export CURL_PRGRS_MAX_FILE_SIZE_BYTES="2097152"
    ## Export CURL_OUT_FILE, so $CURL_PRGRS can read it.
-   export CURL_OUT_FILE="$tb_home_folder/.tb/$TBB_HASH_FILENAME"
+   export CURL_OUT_FILE="$tb_cache_folder/$TBB_HASH_FILENAME"
    curl_download_max_time="180"
    curl_download_target_url="$TBB_HASH_LINK"
    tb_download_common_exit_on_fail="16"
@@ -932,7 +935,7 @@ Downloading:
    ## Export CURL_PRGRS_MAX_FILE_SIZE_BYTES, so $CURL_PRGRS can read it.
    export CURL_PRGRS_MAX_FILE_SIZE_BYTES="104857600"
    ## Export CURL_OUT_FILE, so $CURL_PRGRS can read it.
-   export CURL_OUT_FILE="$tb_home_folder/.tb/$TBB_PACKAGE_FILENAME"
+   export CURL_OUT_FILE="$tb_cache_folder/$TBB_PACKAGE_FILENAME"
    curl_download_max_time="3600"
    curl_download_target_url="$TBB_PACKAGE_LINK"
    tb_download_common_exit_on_fail="17"
@@ -947,9 +950,9 @@ tb_gpg_verify() {
    gpg_bash_lib_input_verify_timeout_after="60"
    gpg_bash_lib_input_verify_kill_after="10"
    gpg_bash_lib_input_key_import_dir="/usr/share/torbrowser-updater-keys.d"
-   gpg_bash_lib_input_temp_folder="$tb_home_folder/.tb/gpgtmpdir"
-   gpg_bash_lib_input_data_file="$tb_home_folder/.tb/$TBB_HASH_FILENAME"
-   gpg_bash_lib_input_sig_file="$tb_home_folder/.tb/$TBB_SIG_FILENAME"
+   gpg_bash_lib_input_temp_folder="$tb_cache_folder/gpgtmpdir"
+   gpg_bash_lib_input_data_file="$tb_cache_folder/$TBB_HASH_FILENAME"
+   gpg_bash_lib_input_sig_file="$tb_cache_folder/$TBB_SIG_FILENAME"
    gpg_bash_lib_input_file_name_enforce="false"
    gpg_bash_lib_input_cleanup="false"
    gpg_bash_lib_input_error_handler_extra='tb_error_handler "$gpg_bash_lib_output_error_handler_message"'
@@ -989,7 +992,7 @@ tb_gpg_verify() {
 tb_hash_verify() {
    output_info_echo_only "Checking hash..."
 
-   rm --force "$tb_home_folder/.tb/sha256_output"
+   rm --force "$tb_cache_folder/sha256_output"
 
    local first second
    local sha256sum_output sha256sum
@@ -999,7 +1002,7 @@ tb_hash_verify() {
    kill_after="30"
 
    ## for relative paths
-   cd "$tb_home_folder/.tb"
+   cd "$tb_cache_folder"
 
    ## Debugging.
    #timeout_after="0.001"
@@ -1010,16 +1013,16 @@ tb_hash_verify() {
    timeout --kill-after="$kill_after" "$timeout_after" \
       sha256sum \
          "$TBB_PACKAGE_FILENAME" \
-         > "$tb_home_folder/.tb/sha256_output" \
+         > "$tb_cache_folder/sha256_output" \
          2>&1 \
          &
 
    lastpid="$!"
    wait "$lastpid" || { tb_sha_exit_code="$?" ; true; };
 
-   sha256sum_output="$(cat "$tb_home_folder/.tb/sha256_output")" || true
+   sha256sum_output="$(cat "$tb_cache_folder/sha256_output")" || true
 
-   if grep -q "$sha256sum_output" "$tb_home_folder/.tb/$TBB_HASH_FILENAME" ; then
+   if grep -q "$sha256sum_output" "$tb_cache_folder/$TBB_HASH_FILENAME" ; then
       output_info_echo_only "Hash check ok."
       return 0
    fi
@@ -1039,14 +1042,14 @@ tb_confirm_install() {
    local last_used_gpg_bash_lib_output_signed_on_date
    local last_used_gpg_bash_lib_output_signed_on_unixtime
 
-   if [ -f "$tb_home_folder/.tb/last_used_gpg_bash_lib_output_signed_on_date" ]; then
-      last_used_gpg_bash_lib_output_signed_on_date="$(cat "$tb_home_folder/.tb/last_used_gpg_bash_lib_output_signed_on_date")" || true
+   if [ -f "$tb_cache_folder/last_used_gpg_bash_lib_output_signed_on_date" ]; then
+      last_used_gpg_bash_lib_output_signed_on_date="$(cat "$tb_cache_folder/last_used_gpg_bash_lib_output_signed_on_date")" || true
    fi
    if [ "$last_used_gpg_bash_lib_output_signed_on_date" = "" ]; then
       last_used_gpg_bash_lib_output_signed_on_date="Unknown. Probably never downloaded a signature before."
    fi
-   if [ -f "$tb_home_folder/.tb/last_used_gpg_bash_lib_output_signed_on_unixtime" ]; then
-      last_used_gpg_bash_lib_output_signed_on_unixtime="$(cat "$tb_home_folder/.tb/last_used_gpg_bash_lib_output_signed_on_unixtime")" || true
+   if [ -f "$tb_cache_folder/last_used_gpg_bash_lib_output_signed_on_unixtime" ]; then
+      last_used_gpg_bash_lib_output_signed_on_unixtime="$(cat "$tb_cache_folder/last_used_gpg_bash_lib_output_signed_on_unixtime")" || true
    fi
    if [ "$last_used_gpg_bash_lib_output_signed_on_unixtime" = "" ]; then
       last_used_gpg_bash_lib_output_signed_on_unixtime="unknown"
@@ -1152,8 +1155,8 @@ y/n?"
       fi
    fi
 
-   echo "$gpg_bash_lib_output_signed_on_date" > "$tb_home_folder/.tb/last_used_gpg_bash_lib_output_signed_on_date"
-   echo "$gpg_bash_lib_output_signed_on_unixtime"  > "$tb_home_folder/.tb/last_used_gpg_bash_lib_output_signed_on_unixtime"
+   echo "$gpg_bash_lib_output_signed_on_date" > "$tb_cache_folder/last_used_gpg_bash_lib_output_signed_on_date"
+   echo "$gpg_bash_lib_output_signed_on_unixtime"  > "$tb_cache_folder/last_used_gpg_bash_lib_output_signed_on_unixtime"
 }
 
 tb_extract() {
@@ -1170,7 +1173,7 @@ Extracting $nice_name... This could take a moment."
    local timeout_after kill_after file_name
    timeout_after="180"
    kill_after="30"
-   file_name="$tb_home_folder/.tb/$TBB_PACKAGE_FILENAME"
+   file_name="$tb_cache_folder/$TBB_PACKAGE_FILENAME"
 
    output_info_echo_only "Extracting $file_name ..."
 
@@ -1185,7 +1188,7 @@ Extracting $nice_name... This could take a moment."
          tar \
             xfv \
             "$file_name" \
-            -C "$tb_home_folder/.tb/" \
+            -C "$tb_cache_folder/" \
             &
 
       lastpid="$!"
@@ -1214,7 +1217,7 @@ Extracting $nice_name... This could take a moment."
             tar \
                xfvJ \
                - \
-               -C "$tb_home_folder/.tb/" \
+               -C "$tb_cache_folder/" \
                < "$tar_fifo" &
       tar_pid="$!"
       last_pid_list+=" $tar_pid"
@@ -1289,7 +1292,7 @@ tb_patch_version_number_own() {
    ## existed. Was later changed. Since TBB's folder structure often changes we
    ## just keep using the folder, create it ourselves and therefore make sure
    ## the script will not break in case of further changes by upstream.
-   mkdir --parents "$tb_home_folder/.tb/tor-browser_$TB_LANG/Docs"
+   mkdir --parents "$tb_cache_folder/tor-browser_$TB_LANG/Docs"
 
    ## Tor Browser changelog has been forgotten to update.
    ## https://sourceforge.net/p/whonix/discussion/general/thread/6122990d/
@@ -1299,17 +1302,17 @@ tb_patch_version_number_own() {
    ## To play it safe and having a chance of finding out the installed version,
    ## we create a file ourselves to remember it.
    output_info_echo_only "Creating version file tor-browser_$TB_LANG/Docs/version."
-   echo "$tbb_version" > "$tb_home_folder/.tb/tor-browser_$TB_LANG/Docs/version"
+   echo "$tbb_version" > "$tb_cache_folder/tor-browser_$TB_LANG/Docs/version"
 }
 
 tb_patch_download_folder_create() {
-   mkdir --parents "$tb_home_folder/.tb/tor-browser_$TB_LANG/Browser/Downloads"
+   mkdir --parents "$tb_cache_folder/tor-browser_$TB_LANG/Browser/Downloads"
 }
 
 tb_patch_internal_updater_disable_maybe() {
    local source_file target_file
    source_file="/usr/share/tb-updater/tb_internal_updater_disable.js"
-   target_file="$tb_home_folder/.tb/tor-browser_$TB_LANG/Browser/TorBrowser/Data/Browser/profile.default/preferences/tb_internal_updater_disable.js"
+   target_file="$tb_cache_folder/tor-browser_$TB_LANG/Browser/TorBrowser/Data/Browser/profile.default/preferences/tb_internal_updater_disable.js"
 
    if dpkg --compare-versions "$tbb_version" ge "4.5" ; then
       output_info_echo_only "No need to deactivate Tor Browser’s Internal \
@@ -1349,8 +1352,8 @@ tb_install() {
       mv "$tb_browser_folder" "$tb_browser_folder.old.$(date '+%F-%H:%M:%S')"
    fi
 
-   output_info_echo_only "Moving temporary folder $tb_home_folder/.tb/tor-browser_$TB_LANG to $tb_browser_folder."
-   mv "$tb_home_folder/.tb/tor-browser_$TB_LANG" "$tb_browser_folder"
+   output_info_echo_only "Moving temporary folder $tb_cache_folder/tor-browser_$TB_LANG to $tb_browser_folder."
+   mv "$tb_cache_folder/tor-browser_$TB_LANG" "$tb_browser_folder"
 }
 
 tb_end() {
