Authenticate file names. This is useful to detect a downgrade or indefinite freeze attack. To do this, the sha256sums.txt file needs to be verified using the sha256sums.txt.asc file. When that succeeded, the hash for the archive needs to be created and looked up within sha256sums.txt. https://phabricator.whonix.org/T98

diff --git a/usr/bin/update-torbrowser b/usr/bin/update-torbrowser
--- a/usr/bin/update-torbrowser
+++ b/usr/bin/update-torbrowser
@@ -796,11 +796,13 @@ tb_download_files() {
       last_try="1"
    fi
 
+   ### signature ###
+
    tb_notify_details="Downloading Tor Browser signature... Will take a moment..."
 
-   [ -n "$TBB_SIG_FILENAME" ] || TBB_SIG_FILENAME="tor-browser-${ARCH_NEW}-${tbb_version}_${TB_LANG}.tar.xz.asc"
-   [ -n "$TBB_EXTRA_FOLDER" ] || TBB_EXTRA_FOLDER="${tbb_version_folder}/"
-   [ -n "$TBB_SIG_LINK" ] || TBB_SIG_LINK="${TBB_REMOTE_FOLDER}/${TBB_EXTRA_FOLDER}${TBB_SIG_FILENAME}"
+   [ -n "$TBB_SIG_FILENAME" ] || TBB_SIG_FILENAME="sha256sums.txt.asc"
+   [ -n "$TBB_EXTRA_FOLDER" ] || TBB_EXTRA_FOLDER="${tbb_version_folder}"
+   [ -n "$TBB_SIG_LINK" ] || TBB_SIG_LINK="${TBB_REMOTE_FOLDER}/${TBB_EXTRA_FOLDER}/${TBB_SIG_FILENAME}"
 
    echo "INFO: Downloading GPG signature... Will take a moment..."
    echo "\
@@ -824,30 +826,73 @@ INFO: Downloading:
 <br></br>There are other recommended versions. Will try to download the next recommended version...</p>
 
 <p>(Debugging information: curl_status_message: $curl_status_message)</p>"
-
          ## No popup message in X. Would be too confusing.
          #$output ${output_opts[@]} --messagex --typex "info" --message "$MSG" --done
-
          $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG" --done
-
          ## return 0, so the loop will tell us to try the next $tbb_version.
          return 0
       else
          MSG="<p>Failed to download: $TBB_SIG_LINK</p>
 
 <p>$DOWNLOAD_FAIL_HELP</p>"
-
          $output ${output_opts[@]} --messagex --typex "error" --message "$MSG" --done
          $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG" --done
          exit 1
       fi
    fi
 
+   ### hash file ###
+
+   tb_notify_details="Downloading Tor Browser sha256sums file... Will take a moment..."
+
+   [ -n "$TBB_HASH_FILENAME" ] || TBB_HASH_FILENAME="sha256sums.txt"
+   [ -n "$TBB_EXTRA_FOLDER" ] || TBB_EXTRA_FOLDER="${tbb_version_folder}"
+   [ -n "$TBB_HASH_LINK" ] || TBB_HASH_LINK="${TBB_REMOTE_FOLDER}/${TBB_EXTRA_FOLDER}/${TBB_HASH_FILENAME}"
+
+   echo "INFO: Downloading sha256sums file... Will take a moment..."
+   echo "\
+INFO: Downloading:
+      $TBB_HASH_LINK ... Will take a moment..."
+
+   ## 1 MB = 1048576 bytes
+   ## 2 MB = 2097152 bytes
+   ## Export CURL_PRGRS_MAX_FILE_SIZE_BYTES, so $CURL_PRGRS can read it.
+   export CURL_PRGRS_MAX_FILE_SIZE_BYTES="2097152"
+   ## Export CURL_OUT_FILE, so $CURL_PRGRS can read it.
+   export CURL_OUT_FILE="$tb_home_folder/.tb/$TBB_HASH_FILENAME"
+   curl_download_max_time="180"
+   curl_download_target_url="$TBB_HASH_LINK"
+   tb_download_common
+
+   ## Check if curl failed.
+   if [ ! "$curl_exit_code" = "0" ]; then
+      if [ "$last_try" = "0" ]; then
+         MSG="<p><b>Failed to download:</b> $TBB_SIG_LINK
+<br></br>There are other recommended versions. Will try to download the next recommended version...</p>
+
+<p>(Debugging information: curl_status_message: $curl_status_message)</p>"
+         ## No popup message in X. Would be too confusing.
+         #$output ${output_opts[@]} --messagex --typex "info" --message "$MSG" --done
+         $output ${output_opts[@]} --messagecli --typecli "info" --message "$MSG" --done
+         ## return 0, so the loop will tell us to try the next $tbb_version.
+         return 0
+      else
+         MSG="<p>Failed to download: $TBB_SIG_LINK</p>
+
+<p>$DOWNLOAD_FAIL_HELP</p>"
+         $output ${output_opts[@]} --messagex --typex "error" --message "$MSG" --done
+         $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG" --done
+         exit 1
+      fi
+   fi
+
+   ### archive file ###
+
    tb_notify_details="Downloading Tor Browser... Will take a while..."
 
    [ -n "$TBB_PACKAGE_FILENAME" ] || TBB_PACKAGE_FILENAME="tor-browser-${ARCH_NEW}-${tbb_version}_${TB_LANG}.tar.xz"
-   [ -n "$TBB_EXTRA_FOLDER" ] || TBB_EXTRA_FOLDER="${tbb_version_folder}/"
-   [ -n "$TBB_PACKAGE_LINK" ] || TBB_PACKAGE_LINK="$TBB_REMOTE_FOLDER/${TBB_EXTRA_FOLDER}$TBB_PACKAGE_FILENAME"
+   [ -n "$TBB_EXTRA_FOLDER" ] || TBB_EXTRA_FOLDER="${tbb_version_folder}"
+   [ -n "$TBB_PACKAGE_LINK" ] || TBB_PACKAGE_LINK="$TBB_REMOTE_FOLDER/${TBB_EXTRA_FOLDER}/$TBB_PACKAGE_FILENAME"
 
    echo "INFO: Downloading Tor Browser Bundle: $tbb_version"
    echo "\
@@ -871,9 +916,7 @@ INFO: Downloading:
 <p>$DOWNLOAD_FAIL_HELP</p>
 
 <p>(Debugging information: curl_status_message: $curl_status_message)</p>"
-
       $output ${output_opts[@]} --progressbaridx "$progressbaridx" --progressx "100" || true
-
       $output ${output_opts[@]} --messagex --typex "error" --message "$MSG" --done
       $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG" --done
       exit 1
@@ -882,7 +925,7 @@ INFO: Downloading:
    tb_download_ok="1"
 }
 
-tb_verify() {
+tb_gpg_verify() {
    echo "INFO:
 ## Verifying GPG signature.
 ## Not using the user's GPG keyring also ensures, that the key can be only
@@ -893,7 +936,7 @@ tb_verify() {
    gpg_bash_lib_input_verify_kill_after="10"
    gpg_bash_lib_input_key_import_dir="/usr/share/torbrowser-updater-keys.d"
    gpg_bash_lib_input_temp_folder="$tb_home_folder/.tb/gpgtmpdir"
-   gpg_bash_lib_input_data_file="$tb_home_folder/.tb/$TBB_PACKAGE_FILENAME"
+   gpg_bash_lib_input_data_file="$tb_home_folder/.tb/$TBB_HASH_FILENAME"
    gpg_bash_lib_input_sig_file="$tb_home_folder/.tb/$TBB_SIG_FILENAME"
    gpg_bash_lib_input_file_name_enforce="true"
    gpg_bash_lib_input_cleanup="false"
@@ -917,6 +960,51 @@ $gpg_bash_lib_output_gpg_verify_output"
       $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG" --done
       exit 1
    fi
+}
+
+tb_hash_verify() {
+   echo "INFO: Checking hash..."
+
+   rm --force "$tb_home_folder/.tb/sha256_output"
+
+   local first second
+   local sha256sum_output sha256sum
+
+   local timeout_after kill_after file_name
+   timeout_after="180"
+   kill_after="30"
+
+   ## for relative paths
+   cd "$tb_home_folder/.tb"
+
+   ## Debugging.
+   #timeout_after="0.001"
+   #kill_after="0.001"
+
+   tb_sha_exit_code="0"
+
+   timeout --kill-after="$kill_after" "$timeout_after" \
+      sha256sum "$TBB_PACKAGE_FILENAME" \
+         > "$tb_home_folder/.tb/sha256_output" \
+         2>&1 \
+         \ &
+
+   lastpid="$!"
+   wait "$lastpid" || { tb_sha_exit_code="$?" ; true; };
+
+   sha256sum_output="$(cat "$tb_home_folder/.tb/sha256_output")" || true
+
+   if grep -q "$sha256sum_output" "$tb_home_folder/.tb/$TBB_HASH_FILENAME" ; then
+      echo "INFO: Hash check ok."
+      return 0
+   fi
+
+   echo "ERROR: Hash check failed! Exiting." >&2
+   local MSG="<p><b>Hash could NOT be verified.</b>
+<br></br>Tor Browser update failed! Try again later.</p>"
+   $output ${output_opts[@]} --messagex --typex "error" --message "$MSG" --done
+   $output ${output_opts[@]} --messagecli --typecli "error" --message "$MSG" --done
+   exit 1
 }
 
 tb_confirm_install() {
@@ -1203,7 +1291,8 @@ main_function() {
    tb_run_function tb_sort_remote_versions
    tb_run_function tb_confirm_update
    tb_run_function tb_download_loop
-   tb_run_function tb_verify
+   tb_run_function tb_gpg_verify
+   tb_run_function tb_hash_verify
    tb_run_function tb_confirm_install
    tb_run_function tb_extract
    tb_run_function tb_patch
